### ISSUE TITLE
Somehow the instant tech bugs the new logistics bots. 

### ISSUE THREAD

**Issue by Mingyuan-Zhang233** [Velociraptor115-DSPModding/ExposeCreativeMode#1]
**Mod**
ExposeCreativeMode 0.0.18

**Describe the bug**
After unlocking tech which upgrades the new bots in 9.27 update using the mod, the tech shows up as researched but the bots are still the same. 

**To Reproduce**
For example, after researching the capacity, the capacity for vessels increases but the capacity of bots doesn't change. 

**Expected behavior**
The bot's stats should be upgraded according to the tech description 

**Environment (please complete the following information):**
OS: Windows 10
Game version: 9.27
Only dependencies and DSPOptimization. 

**Additional context**
Disabling other mods did not help

**Comment by Velociraptor115** [comment]
Thanks for the bug report 😄 
I have not been active for a couple of months now. I will address this next week if time permits.

**Comment by Velociraptor115** [comment]
This should be fixed in version 0.0.19 with the 8a75969 commit

Please re-open the issue if it is still not fixed
